create extension if not exists pgcrypto;

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workflow_checkpoints (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  conversation_id uuid not null references public.conversations(id) on delete restrict,
  request_id text not null,
  workflow_type text not null,
  state text not null,
  version integer not null default 1,
  checkpoint jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, request_id)
);

create table public.conversation_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  conversation_id uuid not null references public.conversations(id) on delete restrict,
  role text not null check (role in ('user', 'assistant', 'tool')),
  content_ciphertext text,
  content_summary text,
  sequence_number bigint generated by default as identity,
  created_at timestamptz not null default now()
);

create table public.approvals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  workflow_checkpoint_id uuid not null references public.workflow_checkpoints(id) on delete restrict,
  preview_hash text not null,
  status text not null check (status in ('pending', 'approved', 'denied', 'expired', 'consumed')),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.conversations enable row level security;
alter table public.workflow_checkpoints enable row level security;
alter table public.approvals enable row level security;
alter table public.conversation_messages enable row level security;

create policy "users manage their conversations"
  on public.conversations for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "users read their checkpoints"
  on public.workflow_checkpoints for select
  using (auth.uid() = user_id);

create policy "users read their approvals"
  on public.approvals for select
  using (auth.uid() = user_id);

create policy "users manage their messages"
  on public.conversation_messages for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index workflow_checkpoints_resume_idx
  on public.workflow_checkpoints (state, updated_at);

create index approvals_pending_idx
  on public.approvals (user_id, status, expires_at);
